version: 2
jobs:
  build:
    docker: 
      - image: circleci/python:3.6.1
    steps:
      - setup_remote_docker: 
          docker_layer_caching: true
      - checkout
      # start proprietary DB using private Docker image
      # with credentials stored in the UI
      - run: |
          DOCKER_CMD=${DOCKER_CMD:-docker}
          $DOCKER_CMD login -u "$DOCKER_USER" -p "$DOCKER_PASS"
          VCS_REF=$(git rev-parse --short HEAD)
          BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          DOCKER_CMD=${DOCKER_CMD:-docker}
          # build the application image
          $DOCKER_CMD build . \
            --build-arg VCS_REF=${VCS_REF} \
            --build-arg BUILD_DATE=${BUILD_DATE} \
            -t alexgmoore/helm-kubectl:${CIRCLE_BRANCH}
          docker push alexgmoore/helm-kubectl:${CIRCLE_BRANCH}
  publish:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      # deploy the image
      - run: |
          if [ -z "${CIRCLE_TAG}" ]; then
            CIRCLE_TAG=latest
          fi
          docker pull alexgmoore/helm-kubectl:${CIRCLE_BRANCH}
          docker tag alexgmoore/helm-kubectl:${CIRCLE_BRANCH} alexgmoore/helm-kubectl:${CIRCLE_TAG}
          docker push alexgmoore/helm-kubectl:${CIRCLE_TAG}

workflows:
  version: 2
  build_and_deploy:
    triggers:
      filters:
        tags:
          only: /^v.*/
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
      - publish:
          filters:
            tags:
              only: /^v.*/
            branches:
              only: master
          requires:
            - build

