version: 2
jobs:
  build:
    machine: true
    docker: 
     # DLC does nothing here, its caching depends on commonality of the image layers.
     - image: alpine:3.9
   steps:
      - setup_remote_docker: 
          docker_layer_caching: true
      - checkout
      # start proprietary DB using private Docker image
      # with credentials stored in the UI
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          # build the application image
          docker build VCS_REF=`git rev-parse --short HEAD` --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` -t alexgmoore/helm-kubectl:$CIRCLE_TAG .
  publish:
    steps:
      # deploy the image
      - run: docker push alexgmoore/helm-kubectl:$CIRCLE_TAG

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
      - deploy:
          filters:
            tags:
              only: /^v.*/
          requires:
            - build

