version: 2
jobs:
  build:
    docker: 
      - image: circleci/python:3.6.1
    steps:
      - setup_remote_docker: 
          docker_layer_caching: true
      - checkout
      # start proprietary DB using private Docker image
      # with credentials stored in the UI
      - run: |
          # docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
          if [ -z "${CIRCLE_TAG}" ]; then
            CIRCLE_TAG=latest
          fi
          VCS_REF=$(git rev-parse --short HEAD)
          BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          # build the application image
          echo docker build . \
            --build-arg VCS_REF=${VCS_REF} \
            --build-arg BUILD_DATE=${BUILD_DATE} \
            -t alexgmoore/helm-kubectl:${CIRCLE_TAG}
  publish:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      # deploy the image
      - run: docker push alexgmoore/helm-kubectl:$CIRCLE_TAG

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
      - publish:
          filters:
            tags:
              only: /^v.*/
            branches:
              only: master
          requires:
            - build

